version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/mautic
    steps:
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo composer self-update
      - run: wget --output-document=mautic.tar.gz https://github.com/mautic/mautic/archive/2.12.1.tar.gz && tar -xzf mautic.tar.gz --strip 1
      - checkout:
          path:
            ~/mautic/plugins/MauticHcaptchaBundle
      - run: composer install --no-scripts --ignore-platform-reqs
      - run: bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter MauticHcaptchaBundle
